// Mocks generated by Mockito 5.4.4 from annotations
// in bookfinderapp/test/features/book_search/domain/usecases/search_books_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bookfinderapp/core/utils/result.dart' as _i4;
import 'package:bookfinderapp/features/book_search/domain/entities/book_search_result.dart'
    as _i5;
import 'package:bookfinderapp/features/book_search/domain/entities/saved_book.dart'
    as _i7;
import 'package:bookfinderapp/features/book_search/domain/repositories/book_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i2.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.BookSearchResult>> searchBooks({
    required String? query,
    int? startIndex = 0,
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [],
          {
            #query: query,
            #startIndex: startIndex,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.BookSearchResult>>.value(
            _i6.dummyValue<_i4.Result<_i5.BookSearchResult>>(
          this,
          Invocation.method(
            #searchBooks,
            [],
            {
              #query: query,
              #startIndex: startIndex,
              #maxResults: maxResults,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.BookSearchResult>>);

  @override
  _i3.Future<_i4.Result<_i5.BookSearchResult>> getBooksByCategory({
    required String? category,
    int? startIndex = 0,
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksByCategory,
          [],
          {
            #category: category,
            #startIndex: startIndex,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.BookSearchResult>>.value(
            _i6.dummyValue<_i4.Result<_i5.BookSearchResult>>(
          this,
          Invocation.method(
            #getBooksByCategory,
            [],
            {
              #category: category,
              #startIndex: startIndex,
              #maxResults: maxResults,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.BookSearchResult>>);

  @override
  _i3.Future<_i4.Result<_i5.BookSearchResult>> getNewestBooks({
    int? startIndex = 0,
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewestBooks,
          [],
          {
            #startIndex: startIndex,
            #maxResults: maxResults,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.BookSearchResult>>.value(
            _i6.dummyValue<_i4.Result<_i5.BookSearchResult>>(
          this,
          Invocation.method(
            #getNewestBooks,
            [],
            {
              #startIndex: startIndex,
              #maxResults: maxResults,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.BookSearchResult>>);

  @override
  _i3.Future<void> saveBook(_i7.SavedBook? book) => (super.noSuchMethod(
        Invocation.method(
          #saveBook,
          [book],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.SavedBook>> getAllSavedBooks() => (super.noSuchMethod(
        Invocation.method(
          #getAllSavedBooks,
          [],
        ),
        returnValue: _i3.Future<List<_i7.SavedBook>>.value(<_i7.SavedBook>[]),
      ) as _i3.Future<List<_i7.SavedBook>>);

  @override
  _i3.Future<_i7.SavedBook?> getSavedBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSavedBook,
          [id],
        ),
        returnValue: _i3.Future<_i7.SavedBook?>.value(),
      ) as _i3.Future<_i7.SavedBook?>);

  @override
  _i3.Future<void> deleteBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isBookSaved(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isBookSaved,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
